### PR TITLE
Inform about unavailable items

### LINKED ISSUE #7: Inform about unavailable items
### Description
- Add another option in the dropdown menu and give it a random food name (which isn't available on the menu board).
- If the user orders it, a text is displayed: _Item unavailable! Order something else._ 
- `Chef` GameObject should also be disabled at this time.

### PR DESCRIPTION
**Pull request by ashwin003**
Resolved [#7](https://github.com/pranshi112/FoodMenu/issues/7)

* Added option "*Noodles*" under available options in the dropdown
* On selection, "Item unavailable! Order something else" will be displayed
* `Chef` GameObject will be hidden

FoodMenu

### CODE REVIEW

**Comment by pranshi112** [comment]
@ashwin003 Before moving any further, first pull the recent changes from this repo to your local one.

**Comment by ashwin003** [comment]
@pranshi112 updated

**Comment by pranshi112** [comment]
> @pranshi112 updated
There are still some changes left to make. Please look at them in the comments.

**Comment by ashwin003** [comment]
@pranshi112, please elaborate. What are the pending changes?

**Comment by pranshi112** [comment]
> @pranshi112, please elaborate. What are the pending changes?

Remove the `?` from line 37 of `DropdownHandler.cs` file. Also, have you done all your work in the 16:9 aspect ratio? The screenshot appears to be of a different aspect ratio. Position your text according to 16:9.

**Comment by ashwin003** [comment]
> Remove the `?` from line 37 of `DropdownHandler.cs` file. Also, have you done all your work in the 16:9 aspect ratio? The screenshot appears to be of a different aspect ratio. Position your text according to 16:9.

I have done my work in 16:9. Here is an updated screenshot:

FoodMenu-New

The `?` is needed as a part of null safety because the `item` object becomes null when you select something from the dropdown that is not available on the menu board

**Comment by pranshi112** [comment]
Great work :)

**Pull request merged**
