### PR TITLE
Create Menu Button

### LINKED ISSUE #3: Create Menu button
### Description
Add a Menu button to toggle the remaining GameObjects on the screen on and off.
- Add a UI button. Position and scale it well.
- Navigate to the `Sprites` folder, select and use the `Menu Icon` sprite on the UI button.
- Make a new script in the `Scripts` folder and add the code for the new functionality.
- Include a screenshot of your changes in the PR description.
- Do all the work in the 16:9 aspect ratio of the game view.

### PR DESCRIPTION
**Pull request by NotFarFromBlonded**
Added a menu button using menu icon sprite to toggle the remaining GameObjects on the screen on and off. 

Initially:
image

After Pressing Menu Button:
image

Pressing the Menu Button Again:
image

fixes #3

### CODE REVIEW

**Review by pranshi112 — CHANGES_REQUESTED** [review]
1. Your branch has merge conflicts. Pull the recent changes from this repo to your local repo.
2. The Menu button toggles off the `Exit` button too which shouldn't happen.
3. I think adding gameobjects in the `handler` array directly through Inspector would be much efficient (there are just 4 to add: Menu Board, Canvas, Food Items, and Chef) instead of creating a whole new function `FindActiveGameObjectsWithLayer()` function.
4. The Menu button's current position looks odd. Maybe add it to the top-left, reduce its size a bit, and drag the Menu Board slightly towards the right. You can also scale the objects if the scene looks congested.

**Comment by pranshi112** [comment]
@NotFarFromBlonded What are commits d7e61ca and d41dbe8? You've also pushed the `Temp` folder in these, which shouldn't be done.

**Comment by NotFarFromBlonded** [comment]
1. Updated UI:
image

2. Exit now doesn't disappear on pressing the menu icon:
image

3. Removed FindActiveGameObjectsWithLayer() function. Now Game Objects can be directly added to the inspector
image

**Comment by NotFarFromBlonded** [comment]
> @NotFarFromBlonded What are commits [d7e61ca](https://github.com/pranshi112/FoodMenu/commit/d7e61cad965d55ea505c9a9bb7724a65f5cdc7bb) and [d41dbe8](https://github.com/pranshi112/FoodMenu/commit/d41dbe83e60a39c4e24631296dbec0ec5afe9aa0)? You've also pushed the `Temp` folder in these, which shouldn't be done.

A few hiccups that I had to deal with while pulling this repo. It's all resolved now.

**Review by pranshi112 — CHANGES_REQUESTED** [review]
Please make the following changes:

1. Remove the commits d7e61ca and d41dbe8 because they would get included when the PR gets merged.
2. The code for the `MenuHandler.cs` file in commit 3e199d3 works fine. The modifications in it in commit a82be3f don't work as expected in one instance. Try this: Don't use the dropdown after the animation begins; instead, press the Menu button twice. The `Chef` gameobject appears, which should actually not.
3. While adding elements in `handler` array, can you add `Canvas` gameobject there and use code to remove the effect from `Menu button` and `Exit Button`? Otherwise, `handler` array would have to be updated everytime a new UI element is added to Canvas.
4. Please pull the recent changes to your repo because commit 3e199d3 also includes changes to README.md.

**Comment by NotFarFromBlonded** [comment]
Did the fixes you asked for

But I don't know how to resolve these conflict issues

**Pull request closed without merging**
